[cvep]
code_file = "./"

[training]
data_root = "./data/"
training_files_glob = "sub-P001_*.xdf"
out_file = "./test.joblib"

[online]
sleep_s = 0.1

[training.features]
target_freq_hz = 6
passband_hz = [ 1, 40,]

[online.input]
lsl_stream_name = "eeg_data"
buffer_size_s = 1.0

[online.output]
lsl_stream_name = "cvep_decoder"
buffer_size_s = 1.0

[online.classifier]
file = "./test.joblib"

[online.eval]
eval_after_type = "time"
eval_after_s = 0.1
eval_after_nsamples = 10

[online.early_stop]

[online.eval.marker]
stream_name = "my_marker_stream"
trigger_marker = [ 1, 2, 3,]
