[cvep]
code_file = './'                         # path to file containing the cvep codes

[training]
data_root = './data/'
training_files_glob = 'sub-P001_*.xdf'   # looked up in data_root
out_file = './test.joblib'

[training.features]
target_freq_hz = 6
passband_hz = [1, 40]

[online]
sleep_s = 0.1                            # time between updates in seconds

[online.input]
lsl_stream_name = 'eeg_data'
buffer_size_s = 1.0

[online.output]
lsl_stream_name = 'cvep_decoder'
buffer_size_s = 1.0

[online.classifier]
file = './test.joblib'


[online.eval]
eval_after_type = 'time'            # 'time', 'nsamples', or 'marker' (if marker, the marker config section must be present)
eval_after_s = 0.1                  # time after which the model is evaluated
eval_after_nsamples = 10            # number of samples after which the model is evaluated

# Optional: Only required if triggering evals on markers is asked for
[online.eval.marker]
stream_name = 'my_marker_stream'
trigger_marker = [1, 2, 3]             # each marker appearance in the list will trigger an evaluation


[online.early_stop]



